"""Most of the models added

Revision ID: efd31178db2a
Revises: 
Create Date: 2024-11-14 14:45:37.066013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'efd31178db2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=15), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('dpid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('binary_path', sa.String(length=200), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_discovery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('switch_id', sa.Integer(), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('packets', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['switch_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('function_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['function_id'], ['functions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goose_analysis_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('stNum', sa.String(length=8), nullable=True),
    sa.Column('sqNum', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_device_id', sa.Integer(), nullable=False),
    sa.Column('destination_device_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=True),
    sa.Column('attributes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['destination_device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['source_device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitoring_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('bandwidth', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packet_captures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('packet_data', postgresql.BYTEA(), nullable=True),
    sa.Column('source_ip', sa.String(length=15), nullable=True),
    sa.Column('destination_ip', sa.String(length=15), nullable=True),
    sa.Column('protocol', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('packet_captures')
    op.drop_table('monitoring_data')
    op.drop_table('links')
    op.drop_table('goose_analysis_data')
    op.drop_table('event_logs')
    op.drop_table('device_functions')
    op.drop_table('asset_discovery')
    op.drop_table('functions')
    op.drop_table('devices')
    # ### end Alembic commands ###
